mopidy:
    image: "mopidy"
    ports:
        - "6680:6680"
        - "6600:6600"
    volumes:
        - fifo:/tmp/snapcast/
        - /Users/pratham/Downloads/Music:/media/music
        - ./mopidydata:/mopidy

snapserver:
    image: "snapserver"
    ports:
        - "1704:1704"
        - "1705:1705"
        - "1780:1780"
    volumes:
        - fifo:/tmp/snapcast/
